### ISSUE TITLE
Error with climate zones

### ISSUE THREAD

**Issue by StuartHaire** [ajurna/ephember#1]
Hi your repo helped me get past the issue connecting but I get the following error for each zone. Can you help?

```2024-11-25` 12:28:25.469 ERROR (MainThread) [homeassistant.components.climate] Error adding entity climate.downstairs for domain climate with platform ephember
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1368, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 469, in state
    hvac_mode = self.hvac_mode
                ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ephember/climate.py", line 152, in hvac_mode
    mode = zone_mode(self._zone)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyephember/pyephember.py", line 248, in zone_mode
    return ZoneMode(zone_pointdata_value(zone, 'MODE'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 350 is not a valid ZoneMode```

**Comment by ajurna** [comment]
ok. what are your modes set to on your zones?

this error is from pyephember not from this code.

the enum is defined here https://github.com/ttroy50/pyephember/blob/b5226cc582c9805aee938dc4bfd4a4a28915b21b/pyephember/pyephember.py#L18
but you are apparently getting a mode of 350? check your zone modes in the app and see if there is a different mode to the ones listed in that enum.

**Comment by StuartHaire** [comment]
Ah, my bad for understanding.

At the time of testing my modes were set to OFF. Not sure why it would be returning a mode or 350?

**Comment by ajurna** [comment]
Try changing all modes and see if you get a different result?

**Comment by StuartHaire** [comment]
Nope same thing no matter what the mode is set too.. Weird

**Comment by ajurna** [comment]
is it always mode 350?

**Comment by StuartHaire** [comment]
Yep always 350
